.de EXX
.PP
.RS
.EX
..
.de EEE
.EE
.RE
..
.TH ICTREE 1
.
.SH NAME
ictree - like tree but interactive
.
.SH SYNOPSIS
.SY ictree
.OP OPTION...
.OP FILE
.YS
.
.SH DESCRIPTION
.BR ictree
is a terminal-based program that takes a list of contents of directories and displays them in a pager similar to
.IR less
where you can fold/unfold directories and quickly jump between them.
.PP
It is useful to browse
.IR locate , \ find
or any other program output that is a list of paths.
.
.SH EXAMPLES
Find something with
.IR locate
and pipe output into
.BR ictree :
.EXX
locate something | ictree
.EEE
.PP
The same applies to any program that can produce a list of paths.
For example, one can use
.IR find
with
.BR ictree
to view current working directory in a nice tree-like format:
.EXX
find | ictree
.EEE
.PP
.BR ictree
can also take a file that contains paths as its first argument:
.EXX
locate something > list.txt
ictree list.txt
.EEE
.PP
ictree supports
.IR vi -like
search functionality.
Extended regular expressions are supported.
If a pattern contains
.B /
character, the search is performed by full paths of items instead of their short names in the list.
.
.SH COMMANDS
All the commands for moving in the pager resemble
.IR less
and
.IR vi
commands.
.
.SS MOVING
.TP
.BR j ,\  <Down>
Move cursor down 1 line
.PP
.TP
.BR k ,\  <Up>
Move cursor up 1 line
.PP
.TP
.BR l ,\  <Right>
Scroll right
.PP
.TP
.BR h ,\  <Left>
Scroll left
.PP
.TP
.BR ^E ,\  <Mouse\ Wheel\ Down>
Scroll down one line
.PP
.TP
.BR ^Y ,\  <Mouse\ Wheel\ Up>
Scroll up one line
.PP
.TP
.BR ^D
Scroll down half-window
.PP
.TP
.BR ^U
Scroll up half-window
.PP
.TP
.BR ^F
Scroll down one window
.PP
.TP
.BR ^B
Scroll up one window
.PP
.TP
.BR g
Move cursor to the top
.PP
.TP
.BR G
Move cursor to the bottom
.PP
.TP
.BR z
Put cursor at the center of window
.PP
.TP
.BR p
Go to parent item
.
.SS OTHERS
.TP
.BR <Enter> ,\  <Mouse\ Left\ Button>
Fold/unfold selected item
.PP
.TP
.BR <Space>
Fold/unfold selected item and move cursor down 1 line
.PP
.TP
.BR /
Search forward for pattern
.PP
.TP
.BR ?
Search backward for pattern
.PP
.TP
.BR n
Repeat previous search
.PP
.TP
.BR N
Repeat previous search in reverse direction
.PP
.TP
.BR y
Copy selected item into X or Wayland clipboard (using this command requires
.IR xsel \ or\  wl-copy
installed, depending on which display server is used)
.PP
.TP
.BR o
Write selected item to standard output and exit
.PP
.TP
.BR q , \ <Esc>
Quit
.PP
.TP
.BR ^Z
Suspend ictree
.
.SH OPTIONS
.TP
.BR \-\-fold ,\  \-f
Fold directories by default.
.PP
.TP
.BR \-\-separator=<C> ,\  \-s\ <C>
Set directory separator to C.
.B /
is the default value.
.PP
.TP
.BR \-\-help ,\  \-h
Print a help message and exit.
.PP
.TP
.BR \-\-version ,\  \-v
Display version information and exit.
.
.SH SEE ALSO
tree(1), find(1), locate(1), less(1)
.
.SH AUTHOR
Written by Nikita Ivanov.
